#!/usr/bin/env node
// Guided first-time setup: asks once, writes server/.env, prints the
// hosting checklists. Run: npm run setup
// (Safe to re-run: backs up any existing server/.env first.)
// Works interactively (TTY) and with piped answers (printf ... | npm run setup).
import readline from 'node:readline';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT = process.cwd();
const ENV_FILE = path.join(ROOT, 'server', '.env');

function readPipedLines() {
  if (process.stdin.isTTY) return null;
  try {
    return fs.readFileSync(0, 'utf8').split('\n');
  } catch {
    return [];
  }
}

async function main() {
  const piped = readPipedLines();
  let pi = 0;
  let rl = null;
  const ask = (q, def = '') => {
    const label = `${q}${def ? ` [${def}]` : ''}: `;
    if (piped) {
      const line = ((piped[pi++] ?? '').trim());
      console.log(`${label}${line}`);
      return Promise.resolve(line || def);
    }
    rl ??= readline.createInterface({ input: process.stdin, output: process.stdout });
    return new Promise((resolve) => {
      rl.question(label, (a) => resolve(a.trim() || def));
    });
  };

  try {
    const out = [];
    out.push('# Maya gateway config — generated by `npm run setup`.');
    out.push('# Keys stay on this server. Never prefix them with VITE_.');
    out.push('');
    out.push('# --- Brain: Google Gemini (free key from aistudio.google.com → Get API key) ---');
    out.push('UPSTREAM_BASE=https://generativelanguage.googleapis.com/v1beta/openai');
    out.push(`UPSTREAM_KEY=${await ask('Gemini API key', '')}`);
    out.push(`UPSTREAM_MODEL=${await ask('Model', 'gemini-3.6-flash')}`);
    out.push('');
    out.push('PORT=8787');
    out.push('SERVE_DIR=./dist');
    out.push('DATA_DIR=./data');
    out.push('');
    out.push('# --- Sharing (leave empty for local-only use) ---');
    const tokenDefault = crypto.randomBytes(16).toString('hex');
    out.push(`GATEWAY_TOKEN=${await ask('Gateway shared secret (Enter for random)', tokenDefault)}`);
    out.push('# ALLOWED_ORIGIN=https://your-domain');
    out.push('# USERS="alice:pw1"   # multi-user login (or: node server/add-user.js <name> <pw>)');
    out.push('');
    out.push('# --- Optional spares/voice ---');
    out.push('# UPSTREAM2_BASE=https://api.groq.com/openai/v1  # + UPSTREAM2_KEY + UPSTREAM2_MODEL');
    out.push('# ELEVENLABS_API_KEY=xi_...   # lifelike female voice');

    if (fs.existsSync(ENV_FILE)) {
      fs.copyFileSync(ENV_FILE, `${ENV_FILE}.bak`);
      console.log('Backed up existing server/.env → server/.env.bak');
    }
    fs.writeFileSync(ENV_FILE, `${out.join('\n')}\n`);
  } finally {
    try {
      rl?.close();
    } catch {
      /* ignore */
    }
  }

  console.log('\nDone. server/.env written.\n');
  console.log('Run locally:  npm run build && npm start  →  http://localhost:8787');
  console.log('Hosting later, you will need (nothing to do now):');
  console.log('  - Same values as Supabase Edge Function secrets (UPSTREAM_*)');
  console.log('  - Vercel env: VITE_API_URL + VITE_GATEWAY_TOKEN (if set above)');
}

void main().then(
  () => process.exit(0),
  (err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  },
);
